# Generated by Django 3.0.6 on 2020-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200625_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SW', 'Sports Wear'), ('S', 'Shirt'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
