# Generated by Django 3.0.6 on 2020-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200625_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('OW', 'Outwear'), ('SW', 'Sports Wear')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('p', 'primary'), ('D', 'danger'), ('S', 'secondary')], max_length=1),
        ),
    ]
